export const NEWSLETTER = {
  SECTION_HEADING: "Get the newsletter",
  PLACEHOLDER: "you@example.com",
  BUTTON_SUBSCRIBE: "Subscribe",
  BUTTON_SUBSCRIBING: "Subscribing...",
  SUCCESS_MESSAGE: "TBD_COPY_SUCCESS_MESSAGE",
  ERROR_INVALID_EMAIL: "TBD_COPY_INVALID_EMAIL_ERROR",
  ERROR_SERVER: "TBD_COPY_SERVER_ERROR",
  PRIVACY_DISCLOSURE: "TBD_COPY_PRIVACY_DISCLOSURE",
};
